wandb: WARNING Calling run.save without any arguments is deprecated.Changes to attributes are automatically persisted.
1
/home/dacon/anaconda3/envs/ct/lib/python3.7/site-packages/albumentations/augmentations/transforms.py:2247: UserWarning: Using lambda is incompatible with multiprocessing. Consider using regular functions or partial().
  warnings.warn('Using lambda is incompatible with multiprocessing. '

Epoch: 0
train:   0%|                                                      | 0/227 [00:00<?, ?it/s]train:   0%|                                                      | 0/227 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "02train.py", line 191, in <module>
    train_logs = train_epoch.run(train_loader)
  File "/home/dacon/anaconda3/envs/ct/lib/python3.7/site-packages/segmentation_models_pytorch/utils/train.py", line 47, in run
    loss, y_pred = self.batch_update(x, y)
  File "/home/dacon/anaconda3/envs/ct/lib/python3.7/site-packages/segmentation_models_pytorch/utils/train.py", line 87, in batch_update
    prediction = self.model.forward(x)
  File "/home/dacon/anaconda3/envs/ct/lib/python3.7/site-packages/segmentation_models_pytorch/base/model.py", line 15, in forward
    features = self.encoder(x)
  File "/home/dacon/anaconda3/envs/ct/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dacon/anaconda3/envs/ct/lib/python3.7/site-packages/segmentation_models_pytorch/encoders/resnet.py", line 62, in forward
    x = stages[i](x)
  File "/home/dacon/anaconda3/envs/ct/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dacon/anaconda3/envs/ct/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/dacon/anaconda3/envs/ct/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dacon/anaconda3/envs/ct/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/dacon/anaconda3/envs/ct/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dacon/anaconda3/envs/ct/lib/python3.7/site-packages/torchvision/models/resnet.py", line 105, in forward
    out = self.bn1(out)
  File "/home/dacon/anaconda3/envs/ct/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dacon/anaconda3/envs/ct/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/home/dacon/anaconda3/envs/ct/lib/python3.7/site-packages/torch/nn/functional.py", line 2058, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 1; 23.70 GiB total capacity; 1.86 GiB already allocated; 11.06 MiB free; 1.88 GiB reserved in total by PyTorch)
